### ISSUE TITLE
Can not compute HR with small face

### ISSUE THREAD

**Issue by RijunLiao** [nasir6/rPPG#3] opened 2019-12-01 10:38 UTC
Dear Sir, I am very interested in your work and many thanks for your work. Could I ask a question? It is fine when the face is large. But it can not compute HR when the face is not large. The HR is NaN. Thank you!

**Comment by nasir6** [comment] 2020-12-24 08:16
Duplicate of #10

**Closed as completed by nasir6** 2020-12-24 08:17 UTC
