### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jaysimon** [nasir6/rPPG#4] opened 2019-12-17 03:31 UTC
when runing this: 
python3 run.py --source=0 --frame-rate=25

got this error:
Segmentation fault (core dumped)

any ideas?

**Comment by nasir6** [comment] 2020-01-23 06:25
Duplicate of #1  please try to download the model weights from the google drive link shared in #1

**Closed as completed** 2020-01-23 06:27 UTC
